#debug模式，true输出控制台日志，false只输出文件日志.生产环境需要关闭debug
debug: true
#名称
server_name: "abs_admin"
#server 地址
server_url: "0.0.0.0:8000"
#缓存介质类型,单选("mem","redis")
cache_type: "mem"
#redis地址(cache_type为“redis”时有效)
redis_url: "redis://127.0.0.1:6379"
#数据库地址
database_url: "sqlite://target/sqlite.db"
#逻辑删除-字段
logic_column: "del"
#逻辑删除-未删除标志
logic_un_deleted: 0
#逻辑删除-已删除标志
logic_deleted: 1
#日志文件目录-可以指定具体名称target/logs/abc.log默认target/logs/
log_dir: "target/logs/"
#日志分割尺寸-单位KB,MB,GB
log_temp_size: "100MB"
#日志类型-可选(大内存机器推荐mmap) mmap,file
log_type: "mmap"
#日志打包格式可选“”（空-保留.log）“gzip”（gz压缩包）“zip”（zip压缩包）“lz4”（lz4压缩包（非常快））
#需要打开以下选项
#toml文件里面，fast_log 添加   fast_log = { version = "1.5",features = ["lz4", "zip", "gzip"]}
#src/config/log.rs    解除   fn choose_packer()下的注释
#application.yml      添加   log_pack_compress: "zip"
log_pack_compress: ""
#日志滚动保留-保留全部: All,按时间保留(秒): KeepTime(i64),按版本保留: KeepNum(i64)
log_rolling_type: "KeepNum(20)"
#日志等级: off,info,error,warn,debug,trace
log_level: "info"
#日志通道长度，null为无界队列，非null为有界队列（性能好）
log_chan_len: 100000
#JwtToken秘钥
jwt_secret: "abs_admin"
#短信通道缓存（系统先把数据放入队列sms:send:，第三方短信sdk或程序需要从队列获取并发送，获得回执存入sms:resp:*）,格式为sms:send:手机号和sms:resp:手机号
sms_cache_send_key_prefix: "sms:send:"
#登陆失败拒绝策略，重试次数限制(0次无限制)
login_fail_retry: 3
#登陆失败重试次数限制超过后提示的等待时间（秒）
login_fail_retry_wait_sec: 30
#接口白名单（免登陆直接访问）
white_list_api:
 - "/"
 - "/admin/sys_login"
 - "/admin/captcha"
#垃圾数据超时，单位:天 (被删除数据超时被永久删除)
trash_recycle_days: 90

errors:
  -1: "未知错误"
  empty: "缺少参数"
  arg.name_empty: "权限名字不能为空"
  arg.permission_empty: "权限不能为空"
  access_token_empty: "令牌不能为空"
  access_denied: "无权限访问"
  account_empty: "账户不能为空"
  cannot_disable_admin: "不能禁用超级管理员"
  dict_exists: "字典已存在"
  permission_exists: "权限已存在"
  role_id_empty: "角色id不能为空"
  please_send_code: "请发送验证码"
  role_user_cannot_empty: "添加角色时用户和角色不能为空"
  user_not_exists: "用户不存在"
  user_and_name_cannot_empty: "用户名和姓名不能为空"
  user_cannot_find: "找不到用户"
  account_not_exists: "账号不存在"
  account_disabled: "账户被禁用"
  password_empty: "密码为空"
  password_error: "密码不正确"
  vcode_error: "验证码不正确"
  req_frequently: "操作过于频繁，请等待{}秒后重试"
  id_empty: "id不能为空"





