[package]
name = "abs_admin"
version = "0.1.0"
authors = ["zhuxiujia <zhuxiujia@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#serde and base types
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4.0"
#log
log = "0.4"
fast_log = "1.2.4"
#runtime
async-std = { version = "1.6", features = ["attributes","tokio02"] }
#rbatis orm dep
rbatis-core = { version = "1.7.24", features = ["all"]}
rbatis =  { version = "1.7.24" }
rbatis-macro-driver = { version = "1.7.24" }

#web server
actix-web = "3"
actix-http = "2.0"

#redis
redis = "0.16.0"

#jwt
jsonwebtoken = "7"
#uuid
uuid = "0.8"
md5 = "0.7.0"

yaml-rust = "0.4"