[package]
name = "abs_admin"
version = "0.1.0"
authors = ["zhuxiujia <zhuxiujia@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#serde and base types
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4.0"
#log
log = "0.4"
fast_log = "1.2.2"
#runtime
tokio = { version = "0.2", features = ["full"] }
#rbatis orm dep
rbatis-core = { version = "1.3.1", features = ["all"]}
rbatis =  { version = "1.3.1" }

#web server
actix-web = "2.0"
actix-rt = "1.0"