[package]
name = "abs_admin"
version = "0.1.0"
authors = ["zhuxiujia <zhuxiujia@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
#rbatis orm dep
rbatis = { version = "1.8", default-features = false, features = ["tokio1-mysql", "snowflake", "debug_mode"] }
#serde and base types
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4.0"
#log
log = "0.4"
fast_log = "1.3"
#runtime
async-std = { version = "1.7", features = ["attributes", "tokio02"] }
#web server
actix-web = "3"
actix-http = "2.0"
#redis
redis = "0.16.0"
#jwt
jsonwebtoken = "7"
#snowflake
rustflake = "0.1.0"
md5 = "0.7.0"
yaml-rust = "0.4"
#captcha
captcha = "0.0.8"

#http client
reqwest = { version = "0.11", features = ["json"] }

#qrcode
qrcode = "0.12"
image = "0.23"